{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idverification365id\/idverificationerror\/clienterror"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientError"}],"title":"IdVerificationError.clientError","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorClientError","modules":[{"name":"IdVerification365id"}]},"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"role":"collection","title":"IdVerification365id","abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","kind":"symbol","type":"topic","url":"\/documentation\/idverification365id"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"role":"symbol","title":"IdVerificationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdVerificationError"}],"abstract":[{"type":"text","text":"Id Verification Errors used in the "},{"type":"codeVoice","code":"onError(error:)"},{"type":"text","text":" method in the "},{"type":"codeVoice","code":"IdVerificationEventDelegate"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IdVerificationError"}],"url":"\/documentation\/idverification365id\/idverificationerror"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/clientError":{"role":"symbol","title":"IdVerificationError.clientError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientError"}],"abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","kind":"symbol","type":"topic","url":"\/documentation\/idverification365id\/idverificationerror\/clienterror"}}}