{"sections":[],"abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"kind":"symbol","metadata":{"title":"IdVerificationError.clientError","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientError"}],"externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorClientError","symbolKind":"case","roleHeading":"Case","modules":[{"name":"IdVerification365id"}]},"variants":[{"paths":["\/documentation\/idverification365id\/idverificationerror\/clienterror"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"clientError","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"navigatorTitle":[{"kind":"identifier","text":"IdVerificationError"}],"title":"IdVerificationError","type":"topic","url":"\/documentation\/idverification365id\/idverificationerror","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdVerificationError","kind":"identifier"}],"abstract":[{"text":"Id Verification Errors used in the ","type":"text"},{"code":"onError(error:)","type":"codeVoice"},{"type":"text","text":" method in the "},{"type":"codeVoice","code":"IdVerificationEventDelegate"}],"kind":"symbol"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","title":"IdVerification365id","url":"\/documentation\/idverification365id","kind":"symbol","role":"collection","type":"topic"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/clientError":{"type":"topic","url":"\/documentation\/idverification365id\/idverificationerror\/clienterror","abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"title":"IdVerificationError.clientError","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"clientError","kind":"identifier"}],"role":"symbol"}}}