{"identifier":{"url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"clientError","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"IdVerification365id"}],"title":"IdVerificationError.clientError","role":"symbol","externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorClientError"},"abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientError"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationerror\/clienterror"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","url":"\/documentation\/idverification365id","kind":"symbol","role":"collection","title":"IdVerification365id"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"navigatorTitle":[{"kind":"identifier","text":"IdVerificationError"}],"abstract":[{"text":"Id Verification Errors used in the ","type":"text"},{"type":"codeVoice","code":"onError(error:)"},{"text":" method in the ","type":"text"},{"type":"codeVoice","code":"IdVerificationEventDelegate"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","url":"\/documentation\/idverification365id\/idverificationerror","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"IdVerificationError","kind":"identifier"}],"title":"IdVerificationError","type":"topic","role":"symbol"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/clientError":{"abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","kind":"symbol","url":"\/documentation\/idverification365id\/idverificationerror\/clienterror","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientError"}],"title":"IdVerificationError.clientError","type":"topic","role":"symbol"}}}