{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientError"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"clientError","kind":"identifier"}],"symbolKind":"case","title":"IdVerificationError.clientError","modules":[{"name":"IdVerification365id"}],"externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorClientError","roleHeading":"Case","role":"symbol"},"abstract":[{"text":"Happens when there is an error caused by something on the device itself","type":"text"}],"identifier":{"url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/idverification365id\/idverificationerror\/clienterror"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"abstract":[{"text":"Id Verification Errors used in the ","type":"text"},{"code":"onError(error:)","type":"codeVoice"},{"type":"text","text":" method in the "},{"type":"codeVoice","code":"IdVerificationEventDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"IdVerificationError"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","url":"\/documentation\/idverification365id\/idverificationerror","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"IdVerificationError","kind":"identifier"}],"title":"IdVerificationError","type":"topic","kind":"symbol"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/clientError":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientError","kind":"identifier"}],"abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"url":"\/documentation\/idverification365id\/idverificationerror\/clienterror","title":"IdVerificationError.clientError","kind":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","type":"topic","role":"symbol"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"type":"topic","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","role":"collection","title":"IdVerification365id","kind":"symbol","url":"\/documentation\/idverification365id","abstract":[]}}}