{"identifier":{"url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","interfaceLanguage":"swift"},"metadata":{"title":"IdVerificationError.clientError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientError","kind":"identifier"}],"role":"symbol","modules":[{"name":"IdVerification365id"}],"roleHeading":"Case","externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorClientError","symbolKind":"case"},"abstract":[{"type":"text","text":"Happens when there is an error caused by something on the device itself"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationerror\/clienterror"]}],"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"clientError","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"IdVerificationError","kind":"identifier"}],"navigatorTitle":[{"text":"IdVerificationError","kind":"identifier"}],"type":"topic","role":"symbol","title":"IdVerificationError","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","kind":"symbol","url":"\/documentation\/idverification365id\/idverificationerror","abstract":[{"type":"text","text":"Id Verification Errors used in the "},{"type":"codeVoice","code":"onError(error:)"},{"type":"text","text":" method in the "},{"code":"IdVerificationEventDelegate","type":"codeVoice"}]},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/clientError":{"title":"IdVerificationError.clientError","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/clientError","kind":"symbol","url":"\/documentation\/idverification365id\/idverificationerror\/clienterror","abstract":[{"text":"Happens when there is an error caused by something on the device itself","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientError","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"url":"\/documentation\/idverification365id","role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","title":"IdVerification365id","type":"topic"}}}