{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationerror\/servererror"]}],"metadata":{"role":"symbol","externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorServerError","title":"IdVerificationError.serverError","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"}],"modules":[{"name":"IdVerification365id"}],"symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/serverError"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Happens when there is an error thrown by the 365id server","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serverError","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/idverification365id","title":"IdVerification365id","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","abstract":[]},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"title":"IdVerificationError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdVerificationError"}],"abstract":[{"type":"text","text":"Id Verification Errors used in the "},{"code":"onError(error:)","type":"codeVoice"},{"type":"text","text":" method in the "},{"code":"IdVerificationEventDelegate","type":"codeVoice"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","url":"\/documentation\/idverification365id\/idverificationerror","navigatorTitle":[{"kind":"identifier","text":"IdVerificationError"}],"role":"symbol"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/serverError":{"type":"topic","abstract":[{"type":"text","text":"Happens when there is an error thrown by the 365id server"}],"title":"IdVerificationError.serverError","kind":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/serverError","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"serverError","kind":"identifier"}],"url":"\/documentation\/idverification365id\/idverificationerror\/servererror"}}}