{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/serverError"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/idverification365id\/idverificationerror\/servererror"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"symbol","symbolKind":"case","title":"IdVerificationError.serverError","modules":[{"name":"IdVerification365id"}],"roleHeading":"Case","externalID":"c:@M@IdVerification365id@E@IdVerificationError@IdVerificationErrorServerError","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Happens when there is an error thrown by the 365id server"}],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError":{"abstract":[{"type":"text","text":"Id Verification Errors used in the "},{"type":"codeVoice","code":"onError(error:)"},{"text":" method in the ","type":"text"},{"type":"codeVoice","code":"IdVerificationEventDelegate"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError","navigatorTitle":[{"kind":"identifier","text":"IdVerificationError"}],"url":"\/documentation\/idverification365id\/idverificationerror","type":"topic","kind":"symbol","title":"IdVerificationError","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdVerificationError"}]},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"kind":"symbol","url":"\/documentation\/idverification365id","type":"topic","role":"collection","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","abstract":[],"title":"IdVerification365id"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationError/serverError":{"url":"\/documentation\/idverification365id\/idverificationerror\/servererror","type":"topic","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationError\/serverError","role":"symbol","title":"IdVerificationError.serverError","abstract":[{"type":"text","text":"Happens when there is an error thrown by the 365id server"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"}],"kind":"symbol"}}}