{"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate"]]},"abstract":[{"type":"text","text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is"},{"text":" ","type":"text"},{"text":"recieved.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IdVerificationErrorBundle","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"onError(_:)","roleHeading":"Instance Method","externalID":"c:@M@IdVerification365id@objc(pl)IdVerificationEventDelegate(im)onError:","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"text":"IdVerificationErrorBundle","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","kind":"typeIdentifier"},{"kind":"text","text":")"}],"required":true,"modules":[{"name":"IdVerification365id"}]},"sections":[],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"title":"IdVerification365id","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","abstract":[],"type":"topic","url":"\/documentation\/idverification365id","kind":"symbol","role":"collection"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate/onError(_:)":{"type":"topic","role":"symbol","url":"\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)","abstract":[{"type":"text","text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is"},{"type":"text","text":" "},{"text":"recieved.","type":"text"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","text":"IdVerificationErrorBundle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"onError(_:)"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate":{"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate","url":"\/documentation\/idverification365id\/idverificationeventdelegate","title":"IdVerificationEventDelegate","role":"symbol","abstract":[{"type":"text","text":"IdVerification SDK event Delegate that is informing about various events"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdVerificationEventDelegate"}],"navigatorTitle":[{"text":"IdVerificationEventDelegate","kind":"identifier"}],"kind":"symbol"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationErrorBundle":{"navigatorTitle":[{"kind":"identifier","text":"IdVerificationErrorBundle"}],"type":"topic","title":"IdVerificationErrorBundle","url":"\/documentation\/idverification365id\/idverificationerrorbundle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdVerificationErrorBundle","kind":"identifier"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","abstract":[{"type":"text","text":"This is a error bundle used to present errors generated from the IdVerification SDK"}],"role":"symbol","kind":"symbol"}}}