{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"IdVerificationErrorBundle","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is"},{"type":"text","text":" "},{"text":"recieved.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@IdVerification365id@objc(pl)IdVerificationEventDelegate(im)onError:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","text":"IdVerificationErrorBundle","kind":"typeIdentifier"},{"kind":"text","text":")"}],"required":true,"modules":[{"name":"IdVerification365id"}],"title":"onError(_:)"},"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationErrorBundle":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"IdVerificationErrorBundle","kind":"identifier"}],"navigatorTitle":[{"text":"IdVerificationErrorBundle","kind":"identifier"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","abstract":[{"type":"text","text":"This is a error bundle used to present errors generated from the IdVerification SDK"}],"url":"\/documentation\/idverification365id\/idverificationerrorbundle","kind":"symbol","type":"topic","title":"IdVerificationErrorBundle","role":"symbol"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","kind":"symbol","url":"\/documentation\/idverification365id","title":"IdVerification365id"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate":{"type":"topic","title":"IdVerificationEventDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IdVerificationEventDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IdVerificationEventDelegate"}],"role":"symbol","url":"\/documentation\/idverification365id\/idverificationeventdelegate","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate","kind":"symbol","abstract":[{"type":"text","text":"IdVerification SDK event Delegate that is informing about various events"}]},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate/onError(_:)":{"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","url":"\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)","title":"onError(_:)","required":true,"abstract":[{"type":"text","text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is"},{"text":" ","type":"text"},{"text":"recieved.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","text":"IdVerificationErrorBundle"},{"kind":"text","text":")"}]}}}