{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)"},"metadata":{"title":"onError(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"IdVerificationErrorBundle","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@M@IdVerification365id@objc(pl)IdVerificationEventDelegate(im)onError:","role":"symbol","symbolKind":"method","required":true,"modules":[{"name":"IdVerification365id"}]},"sections":[],"abstract":[{"type":"text","text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is"},{"text":" ","type":"text"},{"text":"recieved.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","text":"IdVerificationErrorBundle","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate"]]},"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationErrorBundle":{"role":"symbol","type":"topic","url":"\/documentation\/idverification365id\/idverificationerrorbundle","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","navigatorTitle":[{"kind":"identifier","text":"IdVerificationErrorBundle"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdVerificationErrorBundle","kind":"identifier"}],"abstract":[{"text":"This is a error bundle used to present errors generated from the IdVerification SDK","type":"text"}],"title":"IdVerificationErrorBundle","kind":"symbol"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"role":"collection","abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","title":"IdVerification365id","url":"\/documentation\/idverification365id","kind":"symbol","type":"topic"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate":{"navigatorTitle":[{"kind":"identifier","text":"IdVerificationEventDelegate"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdVerificationEventDelegate"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"IdVerification SDK event Delegate that is informing about various events","type":"text"}],"url":"\/documentation\/idverification365id\/idverificationeventdelegate","title":"IdVerificationEventDelegate"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate/onError(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IdVerificationErrorBundle","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle"},{"text":")","kind":"text"}],"title":"onError(_:)","type":"topic","role":"symbol","required":true,"abstract":[{"type":"text","text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is"},{"text":" ","type":"text"},{"type":"text","text":"recieved."}],"kind":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","url":"\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)"}}}