{"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onError"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","kind":"typeIdentifier","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","text":"IdVerificationErrorBundle"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"recieved."}],"variants":[{"paths":["\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)"},"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate"]]},"metadata":{"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@IdVerification365id@objc(pl)IdVerificationEventDelegate(im)onError:","title":"onError(_:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"text":"IdVerificationErrorBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle"},{"kind":"text","text":")"}],"required":true,"modules":[{"name":"IdVerification365id"}]},"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"title":"IdVerification365id","type":"topic","kind":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","role":"collection","url":"\/documentation\/idverification365id","abstract":[]},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate":{"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate","kind":"symbol","abstract":[{"text":"IdVerification SDK event Delegate that is informing about various events","type":"text"}],"type":"topic","url":"\/documentation\/idverification365id\/idverificationeventdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IdVerificationEventDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"IdVerificationEventDelegate","kind":"identifier"}],"title":"IdVerificationEventDelegate"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate/onError(_:)":{"url":"\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","required":true,"title":"onError(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"text":"IdVerificationErrorBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"recieved."}],"type":"topic"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationErrorBundle":{"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","abstract":[{"text":"This is a error bundle used to present errors generated from the IdVerification SDK","type":"text"}],"kind":"symbol","url":"\/documentation\/idverification365id\/idverificationerrorbundle","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IdVerificationErrorBundle","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IdVerificationErrorBundle"}],"title":"IdVerificationErrorBundle"}}}