{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is","type":"text"},{"text":" ","type":"text"},{"text":"recieved.","type":"text"}],"metadata":{"required":true,"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onError"},{"text":"(","kind":"text"},{"text":"IdVerificationErrorBundle","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"IdVerification365id"}],"title":"onError(_:)","externalID":"c:@M@IdVerification365id@objc(pl)IdVerificationEventDelegate(im)onError:","roleHeading":"Instance Method","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","text":"IdVerificationErrorBundle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate"]]},"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"abstract":[],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","title":"IdVerification365id","url":"\/documentation\/idverification365id","kind":"symbol","role":"collection","type":"topic"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate":{"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate","kind":"symbol","type":"topic","title":"IdVerificationEventDelegate","url":"\/documentation\/idverification365id\/idverificationeventdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdVerificationEventDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"IdVerification SDK event Delegate that is informing about various events"}],"navigatorTitle":[{"kind":"identifier","text":"IdVerificationEventDelegate"}],"role":"symbol"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate/onError(_:)":{"type":"topic","kind":"symbol","url":"\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)","title":"onError(_:)","abstract":[{"text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"recieved."}],"required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"kind":"text","text":"("},{"text":"IdVerificationErrorBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationErrorBundle":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"IdVerificationErrorBundle","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/idverification365id\/idverificationerrorbundle","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","abstract":[{"text":"This is a error bundle used to present errors generated from the IdVerification SDK","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IdVerificationErrorBundle"}],"title":"IdVerificationErrorBundle","type":"topic"}}}