{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)"},"abstract":[{"type":"text","text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is"},{"text":" ","type":"text"},{"type":"text","text":"recieved."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onError"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IdVerificationErrorBundle","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate"]]},"metadata":{"externalID":"c:@M@IdVerification365id@objc(pl)IdVerificationEventDelegate(im)onError:","title":"onError(_:)","symbolKind":"method","role":"symbol","modules":[{"name":"IdVerification365id"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IdVerificationErrorBundle","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true},"variants":[{"paths":["\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate":{"title":"IdVerificationEventDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdVerificationEventDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate","abstract":[{"text":"IdVerification SDK event Delegate that is informing about various events","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IdVerificationEventDelegate"}],"kind":"symbol","url":"\/documentation\/idverification365id\/idverificationeventdelegate"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id":{"type":"topic","url":"\/documentation\/idverification365id","title":"IdVerification365id","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id","role":"collection"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationEventDelegate/onError(_:)":{"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationEventDelegate\/onError(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onError","kind":"identifier"},{"kind":"text","text":"("},{"text":"IdVerificationErrorBundle","preciseIdentifier":"c:@M@IdVerification365id@objc(cs)IdVerificationErrorBundle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","required":true,"role":"symbol","abstract":[{"type":"text","text":"Called when there is an error with the sdk. A verification transaction can not be recovered after this call is"},{"type":"text","text":" "},{"type":"text","text":"recieved."}],"url":"\/documentation\/idverification365id\/idverificationeventdelegate\/onerror(_:)","title":"onError(_:)"},"doc://com.365id.sdk.idverification/documentation/IdVerification365id/IdVerificationErrorBundle":{"type":"topic","title":"IdVerificationErrorBundle","url":"\/documentation\/idverification365id\/idverificationerrorbundle","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IdVerificationErrorBundle"}],"identifier":"doc:\/\/com.365id.sdk.idverification\/documentation\/IdVerification365id\/IdVerificationErrorBundle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IdVerificationErrorBundle","kind":"identifier"}],"abstract":[{"type":"text","text":"This is a error bundle used to present errors generated from the IdVerification SDK"}]}}}